/*
 * generated by Xtext 2.26.0
 */
package org.xtext.classifier.dsl.ide;


/**
 * Use this class to register ide components.
 */
public class PClassifierIdeModule extends AbstractPClassifierIdeModule {
}
