/*
 * generated by Xtext 2.26.0
 */
package org.xtext.classifier.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.classifier.dsl.PClassifierRuntimeModule;
import org.xtext.classifier.dsl.PClassifierStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PClassifierIdeSetup extends PClassifierStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PClassifierRuntimeModule(), new PClassifierIdeModule()));
	}
	
}
