/*
 * generated by Xtext 2.26.0
 */
package org.xtext.classifier.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPClassifierScopeProvider extends DelegatingScopeProvider {
}
