/*
 * generated by Xtext 2.26.0
 */
package org.xtext.classifier.dsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.classifier.dsl.ui.internal.DslActivator;

public class PClassifierUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("org.xtext.classifier.dsl.PClassifier");
	}

}
