/*
 * generated by Xtext 2.26.0
 */
package org.xtext.classifier.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PClassifierStandaloneSetup extends PClassifierStandaloneSetupGenerated {

	public static void doSetup() {
		new PClassifierStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
