/*
 * generated by Xtext 2.26.0
 */
package org.xtext.classifier.dsl.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.classifier.dsl.services.PClassifierGrammarAccess;

@SuppressWarnings("all")
public class PClassifierSyntacticSequencer extends AbstractSyntacticSequencer {

	protected PClassifierGrammarAccess grammarAccess;
	protected AbstractElementAlias match_EvaluationList_CommaKeyword_0_a;
	protected AbstractElementAlias match_EvaluationList_CommaKeyword_2_0_p;
	protected AbstractElementAlias match_EvaluationList_CommaKeyword_3_a;
	protected AbstractElementAlias match_FeatureList_CommaKeyword_0_a;
	protected AbstractElementAlias match_FeatureList_CommaKeyword_2_0_p;
	protected AbstractElementAlias match_FeatureList_CommaKeyword_3_a;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (PClassifierGrammarAccess) access;
		match_EvaluationList_CommaKeyword_0_a = new TokenAlias(true, true, grammarAccess.getEvaluationListAccess().getCommaKeyword_0());
		match_EvaluationList_CommaKeyword_2_0_p = new TokenAlias(true, false, grammarAccess.getEvaluationListAccess().getCommaKeyword_2_0());
		match_EvaluationList_CommaKeyword_3_a = new TokenAlias(true, true, grammarAccess.getEvaluationListAccess().getCommaKeyword_3());
		match_FeatureList_CommaKeyword_0_a = new TokenAlias(true, true, grammarAccess.getFeatureListAccess().getCommaKeyword_0());
		match_FeatureList_CommaKeyword_2_0_p = new TokenAlias(true, false, grammarAccess.getFeatureListAccess().getCommaKeyword_2_0());
		match_FeatureList_CommaKeyword_3_a = new TokenAlias(true, true, grammarAccess.getFeatureListAccess().getCommaKeyword_3());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_EvaluationList_CommaKeyword_0_a.equals(syntax))
				emit_EvaluationList_CommaKeyword_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_EvaluationList_CommaKeyword_2_0_p.equals(syntax))
				emit_EvaluationList_CommaKeyword_2_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_EvaluationList_CommaKeyword_3_a.equals(syntax))
				emit_EvaluationList_CommaKeyword_3_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_FeatureList_CommaKeyword_0_a.equals(syntax))
				emit_FeatureList_CommaKeyword_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_FeatureList_CommaKeyword_2_0_p.equals(syntax))
				emit_FeatureList_CommaKeyword_2_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_FeatureList_CommaKeyword_3_a.equals(syntax))
				emit_FeatureList_CommaKeyword_3_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ','*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) vals+=Evaluation
	 
	 * </pre>
	 */
	protected void emit_EvaluationList_CommaKeyword_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ','+
	 *
	 * This ambiguous syntax occurs at:
	 *     vals+=Evaluation (ambiguity) vals+=Evaluation
	 
	 * </pre>
	 */
	protected void emit_EvaluationList_CommaKeyword_2_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ','*
	 *
	 * This ambiguous syntax occurs at:
	 *     vals+=Evaluation (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_EvaluationList_CommaKeyword_3_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ','*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) vals+=STRING
	 
	 * </pre>
	 */
	protected void emit_FeatureList_CommaKeyword_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ','+
	 *
	 * This ambiguous syntax occurs at:
	 *     vals+=STRING (ambiguity) vals+=STRING
	 
	 * </pre>
	 */
	protected void emit_FeatureList_CommaKeyword_2_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ','*
	 *
	 * This ambiguous syntax occurs at:
	 *     vals+=STRING (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_FeatureList_CommaKeyword_3_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
