/**
 * generated by Xtext 2.26.0
 */
package org.xtext.classifier.dsl.pClassifier;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Classifier</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.classifier.dsl.pClassifier.Classifier#getFeatures <em>Features</em>}</li>
 *   <li>{@link org.xtext.classifier.dsl.pClassifier.Classifier#getTarget <em>Target</em>}</li>
 *   <li>{@link org.xtext.classifier.dsl.pClassifier.Classifier#getModel <em>Model</em>}</li>
 * </ul>
 *
 * @see org.xtext.classifier.dsl.pClassifier.PClassifierPackage#getClassifier()
 * @model
 * @generated
 */
public interface Classifier extends Statement
{
  /**
   * Returns the value of the '<em><b>Features</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Features</em>' containment reference.
   * @see #setFeatures(FeatureList)
   * @see org.xtext.classifier.dsl.pClassifier.PClassifierPackage#getClassifier_Features()
   * @model containment="true"
   * @generated
   */
  FeatureList getFeatures();

  /**
   * Sets the value of the '{@link org.xtext.classifier.dsl.pClassifier.Classifier#getFeatures <em>Features</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Features</em>' containment reference.
   * @see #getFeatures()
   * @generated
   */
  void setFeatures(FeatureList value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' attribute.
   * @see #setTarget(String)
   * @see org.xtext.classifier.dsl.pClassifier.PClassifierPackage#getClassifier_Target()
   * @model
   * @generated
   */
  String getTarget();

  /**
   * Sets the value of the '{@link org.xtext.classifier.dsl.pClassifier.Classifier#getTarget <em>Target</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' attribute.
   * @see #getTarget()
   * @generated
   */
  void setTarget(String value);

  /**
   * Returns the value of the '<em><b>Model</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.classifier.dsl.pClassifier.MLModel}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Model</em>' attribute.
   * @see org.xtext.classifier.dsl.pClassifier.MLModel
   * @see #setModel(MLModel)
   * @see org.xtext.classifier.dsl.pClassifier.PClassifierPackage#getClassifier_Model()
   * @model
   * @generated
   */
  MLModel getModel();

  /**
   * Sets the value of the '{@link org.xtext.classifier.dsl.pClassifier.Classifier#getModel <em>Model</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Model</em>' attribute.
   * @see org.xtext.classifier.dsl.pClassifier.MLModel
   * @see #getModel()
   * @generated
   */
  void setModel(MLModel value);

} // Classifier
