/**
 * generated by Xtext 2.26.0
 */
package org.xtext.classifier.dsl.pClassifier;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Feature List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.classifier.dsl.pClassifier.FeatureList#getVals <em>Vals</em>}</li>
 * </ul>
 *
 * @see org.xtext.classifier.dsl.pClassifier.PClassifierPackage#getFeatureList()
 * @model
 * @generated
 */
public interface FeatureList extends EObject
{
  /**
   * Returns the value of the '<em><b>Vals</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vals</em>' attribute list.
   * @see org.xtext.classifier.dsl.pClassifier.PClassifierPackage#getFeatureList_Vals()
   * @model unique="false"
   * @generated
   */
  EList<String> getVals();

} // FeatureList
