/**
 * generated by Xtext 2.26.0
 */
package org.xtext.classifier.dsl.pClassifier;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Run</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.classifier.dsl.pClassifier.Run#getDataset <em>Dataset</em>}</li>
 *   <li>{@link org.xtext.classifier.dsl.pClassifier.Run#getSplit <em>Split</em>}</li>
 *   <li>{@link org.xtext.classifier.dsl.pClassifier.Run#getEvaluation <em>Evaluation</em>}</li>
 * </ul>
 *
 * @see org.xtext.classifier.dsl.pClassifier.PClassifierPackage#getRun()
 * @model
 * @generated
 */
public interface Run extends Statement
{
  /**
   * Returns the value of the '<em><b>Dataset</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dataset</em>' attribute.
   * @see #setDataset(String)
   * @see org.xtext.classifier.dsl.pClassifier.PClassifierPackage#getRun_Dataset()
   * @model
   * @generated
   */
  String getDataset();

  /**
   * Sets the value of the '{@link org.xtext.classifier.dsl.pClassifier.Run#getDataset <em>Dataset</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dataset</em>' attribute.
   * @see #getDataset()
   * @generated
   */
  void setDataset(String value);

  /**
   * Returns the value of the '<em><b>Split</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Split</em>' attribute.
   * @see #setSplit(double)
   * @see org.xtext.classifier.dsl.pClassifier.PClassifierPackage#getRun_Split()
   * @model
   * @generated
   */
  double getSplit();

  /**
   * Sets the value of the '{@link org.xtext.classifier.dsl.pClassifier.Run#getSplit <em>Split</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Split</em>' attribute.
   * @see #getSplit()
   * @generated
   */
  void setSplit(double value);

  /**
   * Returns the value of the '<em><b>Evaluation</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.classifier.dsl.pClassifier.Evaluation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Evaluation</em>' attribute.
   * @see org.xtext.classifier.dsl.pClassifier.Evaluation
   * @see #setEvaluation(Evaluation)
   * @see org.xtext.classifier.dsl.pClassifier.PClassifierPackage#getRun_Evaluation()
   * @model
   * @generated
   */
  Evaluation getEvaluation();

  /**
   * Sets the value of the '{@link org.xtext.classifier.dsl.pClassifier.Run#getEvaluation <em>Evaluation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Evaluation</em>' attribute.
   * @see org.xtext.classifier.dsl.pClassifier.Evaluation
   * @see #getEvaluation()
   * @generated
   */
  void setEvaluation(Evaluation value);

} // Run
