/*
 * generated by Xtext 2.26.0
 */
package org.xtext.classifier.dsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.classifier.dsl.parser.antlr.internal.InternalPClassifierParser;
import org.xtext.classifier.dsl.services.PClassifierGrammarAccess;

public class PClassifierParser extends AbstractAntlrParser {

	@Inject
	private PClassifierGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPClassifierParser createParser(XtextTokenStream stream) {
		return new InternalPClassifierParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "PClassfier";
	}

	public PClassifierGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PClassifierGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
