/*
 * generated by Xtext 2.26.0
 */
package org.xtext.classifier.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PClassifierUiModule extends AbstractPClassifierUiModule {

	public PClassifierUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
